### ISSUE TITLE
Filter projects by ACTIVE status

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec-gcp#108]
At the moment, with the [gcp_projects](https://github.com/inspec/inspec-gcp/blob/master/docs/resources/google_projects.md) is possible to filter by project_id; project_name and project_number.

In a scenario where one is verifying the state of resources and the project name is like `/^foo/`, but there are *two* projects called `foo` with one of them scheduled for deletion, that will cause tests to fail because: 

> ×  Subnetwork platform-engineering-01-test
     Project XXXXXX has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.

But that's not a real failure, as something that does not exist anymore can't be tested.

It would be great to have the ability to filter by project status. Or completely discard projects which are not active (therefore not implementing the filter at all).

Does that make sense?
What do you think?

**Comment by walterdolce** [comment]
Note, the above was raised because I don't necessarily know (and/or want to) the project id of a project (which may be randomly generated). But I *do* know the project name (provided it follows a certain naming convention).

For example:
```
gcp_project_name: my-project
```

Then with some automation that creates projects with semi-random ids, like so:
```
gcp_project_id: "{{ gcp_project_name }}-{{ 9999999 | random }}"
```

The above has been "Ansible-ified", but I think you get the idea 😄

**Comment by skpaterson** [comment]
Makes sense 👍 will look at your PR now.
