### ISSUE TITLE
add missing documentation

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec-gcp#11]
It is challenging to see how the available resources can be used. It would be awesome, if we could have the resources documented similar to https://www.inspec.io/docs/reference/resources/

**Comment by pollosp** [comment]
Sure you know it , but if someone is looking while you update it, here is good doc 
https://lollyrock.com/articles/inspec-cloud-gcp-setup/

**Comment by darkn3rd** [comment]
This is what I was wondering, from the current documentation, the whole purpose is to configure GCP so that you can run `bundle exec rake  test:run_integration_tests`.  There's no documentation about how to actually install or use this with InSpec.
