### ISSUE TITLE
Add support for google_folders and related resources

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec-gcp#111]
This is a placeholder issue which depends on inspec/train#412. Once that is resolved I will be more than happy to implement the resources, if you don't mind!

**Comment by slevenick** [comment]
Which related resources are you referring to? The only v2 resource referenced [here](https://cloud.google.com/resource-manager/reference/rest/) is folders.

I'm happy to add these resources via the REST API, currently working on folders.

**Comment by walterdolce** [comment]
@slevenick google_folders and google_folder

**Comment by slevenick** [comment]
Ok, working on those via APIs directly rather than using the client libraries.

**Comment by slevenick** [comment]
Available at https://github.com/inspec/inspec-gcp/blob/master/libraries/google_resourcemanager_folder.rb

and https://github.com/inspec/inspec-gcp/blob/master/libraries/google_resourcemanager_folders.rb

**Comment by skpaterson** [comment]
@walterdolce I'm going to close this out but let us know if there are any issues!
