### ISSUE TITLE
Add support for google_compute_backend_bucket

### ISSUE THREAD

**Issue by lucashanke** [inspec/inspec-gcp#121]
Nowadays, InSpec only supports google_compute_backend_service and google_compute_backend_services. It would be really helpful to have support enabled for [google_compute_backend_bucket](https://www.terraform.io/docs/providers/google/r/compute_backend_bucket.html), as it has a very similar API.

**Comment by slevenick** [comment]
Find this resource here: https://github.com/inspec/inspec-gcp/blob/master/libraries/google_compute_backend_bucket.rb

**Comment by skpaterson** [comment]
I'll close this out given the resource is available.  Feel free to reopen if something is missing!
