### ISSUE TITLE
Fix dataset test display

### ISSUE THREAD

**Issue by katie-murphy-ck** [inspec/inspec-gcp#125]
When running tests against a BQ dataset, rather than a pretty display in the test like "Firewall Rule my_tag_name", it just gives some internal address/name.
To reproduce: run a valid test against a dataset. Here's my example that gave me this issue (to be clear, the test results were all valid).
```
control 'no-public-datasets' do
  impact 1.0
  title 'public-bq-datasets-check'
  google_bigquery_datasets(project: gcp_project_id).dataset_references.each do |dataset_ref|
    google_bigquery_dataset(project: gcp_project_id, name: dataset_ref.dataset_id).access.each do |dataset_access|
      describe dataset_access do
        its('special_group') { should_not cmp 'allUsers' }
        its('special_group') { should_not cmp 'allAuthenticatedUsers' }
      end
    end
  end
end
```

**Comment by katie-murphy-ck** [comment]
Attempted a fix in PR 123 https://github.com/inspec/inspec-gcp/pull/123

**Comment by slevenick** [comment]
Looking into a way to programmatically add `to_s` blocks with human readable descriptions to all MM generated objects and nested objects.

**Comment by slevenick** [comment]
This issue should be fixed with https://github.com/inspec/inspec-gcp/pull/127
