### ISSUE TITLE
Add support for testing org policy constraints

### ISSUE THREAD

**Issue by katie-murphy-ck** [inspec/inspec-gcp#126]
Want to be able to test that I have certain policy constraints on my orgs.

**Comment by slevenick** [comment]
I believe this is similar to https://github.com/inspec/inspec-gcp/issues/122.

I'm working on creating a way to reuse some code to generate policy/binding InSpec resources for various GCP resource types

**Comment by slevenick** [comment]
Are you looking for organization's IAM policy? Seen here: https://cloud.google.com/resource-manager/reference/rest/v1/organizations/getIamPolicy

Or the organization policy? Seen here: https://cloud.google.com/resource-manager/reference/rest/v1/organizations/getOrgPolicy

**Comment by katie-murphy-ck** [comment]
No, I mean org policy constraints.
https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints

**Comment by katie-murphy-ck** [comment]
...and by "no" I mean "yes."

**Comment by slevenick** [comment]
I believe https://github.com/inspec/inspec-gcp/blob/master/libraries/google_organization_policy.rb addresses this issue. Let me know if there are other use cases that aren't covered

**Comment by slevenick** [comment]
Oh no I mixed up the docs

I'll get that updated, but in the mean time it should work like this:
```
describe google_organization_policy(name: 'organizations/123456', constraint: 'constraints/compute.disableGuestAttributesAccess') do
  it { should exist }
  its('boolean_policy.enforced') { should be true }
end
```

Or 
describe google_organization_policy(name: 'organizations/123456', constraint: 'constraints/someListConstraint') do
  it { should exist }
  its('list_policy.allowed_values') { should include 'included_val' }
  its('list_policy.allowed_values') { should_not include 'excluded' }
  its('list_policy.denied_values') { should include 'denied' }
end
```

Full documentation of the fields available can be found here: https://cloud.google.com/resource-manager/reference/rest/v1/Policy

**Comment by katie-murphy-ck** [comment]
Yes, PR#148 has the right documentation.

**Comment by skpaterson** [comment]
Closing out since #148 resolved the documentation issue. Feel free to reopen if anything is outstanding.
