### ISSUE TITLE
google_compute_router: iterating bgp.advertised_ip_ranges?

### ISSUE THREAD

**Issue by supertylerc** [inspec/inspec-gcp#128]
I'm certain I'm doing something wrong, but I'm looking at the `google_compute_router` resource and the `bgp.advertised_ip_ranges` property specificially.  The documentation uses `bgp.advertised_ip_ranges.first` and `.last`, which works great...if you have two or fewer advertised IP ranges.  However, when you have >= 3, you're missing everything in between.  I'm sure this is probably documented elsewhere, but I couldn't find it.  :(

How can I loop through each possible advertised IP range, or get an _actual_ list of them instead of an object/list of objects?

**Comment by slevenick** [comment]
One way to do this would be to construct the `google_compute_router` outside of the `describe` block, as this gives you access to it as a normal ruby object.

For example:
```
router = google_compute_router(project: 'project', region: 'your-region', name: 'router-name')
describe router do
  (normal test stuff here)
end

# router.bgp.advertised_ip_ranges specific tests here
router.bgp.advertised_ip_ranges.each do |ip_range|
  describe range do
     its('ip_range') { should eq '1.2.3.4' }
  end
end
```

I can improve the documentation examples on this.

Also I wonder if @skpaterson has other ideas

**Comment by supertylerc** [comment]
Thanks, @slevenick!  Here's what I came up with:

```ruby
control '1.0-gcp-cloud-router' do
  impact 1.0
  title "Ensure Cloud Router's Unique Properties"
  rtr = google_compute_router(project: 'my-project', region: 'myr-region', name: 'my-router')
  ip_ranges = rtr.bgp.advertised_ip_ranges.map {|n| n.range }.sort!
  describe ip_ranges do
    it { should eq ["192.168.0.0/24", "192.168.1.0/24", "192.168.2.0/24"] }
  end
end
```

**Comment by supertylerc** [comment]
@slevenick, from my side, this issue can be closed if you'd like.

**Comment by skpaterson** [comment]
+1 to @slevenick's solution.  In more complex cases it can sometimes be worth crafting a custom resource to improve the syntax but for a list this works well.  Thanks @supertylerc I'll close this out.
