### ISSUE TITLE
Release process clarification

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec-gcp#131]
Hi all. What's the release process adopted in this project?

I was pulling v0.9.0 and expecting my recent changes to be there (i.e. #109) but they are not there 🤔

**Comment by walterdolce** [comment]
To clarify the question above, I am aware of there is some information about [release cycles](https://github.com/inspec/inspec-gcp/blob/master/CONTRIBUTING.md#release-cycles), but that does not explicitly say anything about the PRs that get merged and when they will be released (if ever).

Thanks!

**Comment by skpaterson** [comment]
Hi @walterdolce fair point, this has been mostly a manual process up to now but improving that is on the to-do list.

**Comment by walterdolce** [comment]
Glad to hear @skpaterson! Happy to help if needed.

**Comment by skpaterson** [comment]
Happy to say we've moved to a working automated release setup since #168 so each merged PR will now minimally bump the patch version and create a release tag.

**Comment by walterdolce** [comment]
Excellent work! Thanks!
