### ISSUE TITLE
Support for GKE Regional Node Pools

### ISSUE THREAD

**Issue by bgeesaman** [inspec/inspec-gcp#135]
I see that https://github.com/inspec/inspec-gcp/blob/master/libraries/google_container_regional_cluster.rb recently added support for regional GKE clusters, but I think we’re missing support for regional node pools.  Could that be added, please? :-)

Also, if I’m not mistaken, https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/ContainerV1beta1/CreateClusterRequest let’s you make either a zonal or a regional cluster based on the format of parent = “projects/my-project/locations/us-east4” or “projects/my-project/locations/us-east4-a” for regional or zonal, respectively.  That might allow for consildating the container cluster classes into one.

Thank you!

**Comment by slevenick** [comment]
Can add this, but it requires some unrelated work to upgrade terraform to a newer version

**Comment by slevenick** [comment]
There was a workaround. Will be added with https://github.com/inspec/inspec-gcp/pull/139

**Comment by slevenick** [comment]
This can be closed, this resource has been added.

**Comment by skpaterson** [comment]
Closing out as above.
