### ISSUE TITLE
Backend only supports global, what about regional?

### ISSUE THREAD

**Issue by edward2a** [inspec/inspec-gcp#146]
Hi everyone,

I was scratching my head wondering why backend_service resource kept coming back empty.
It seems this resource only supports global backends.
Any chance for regional?

The self link path for the regional resource is:
    projects/{{project}}/regions/{{region}}/backendServices/{{name}}

Cheers,
Ed

https://github.com/inspec/inspec-gcp/blob/a6d34928b601b9ea020fa9c561934302ec4d9003/libraries/google_compute_backend_service.rb#L97

**Comment by slevenick** [comment]
Hey @edward2a 

I can add the regional version of the backend service! Should be ready sometime this week

**Comment by edward2a** [comment]
Awesome stuff, that would make for a nice integration test on the TF modules we are working :)
Thanks @slevenick !

**Comment by slevenick** [comment]
See https://github.com/inspec/inspec-gcp/blob/master/libraries/google_compute_region_backend_service.rb

**Comment by skpaterson** [comment]
Looks like this is now resolved, please reopen if not!
