### ISSUE TITLE
Adding feature to verify the pubsub subscription IAM member

### ISSUE THREAD

**Issue by JonathanLachapelle** [inspec/inspec-gcp#147]
I’m trying to use inspec to verify if my Google pubsub subscription has the right member in it, is it possible to create a feature for this?

Here’s the terraform I’m using to add a member :
https://www.terraform.io/docs/providers/google/r/pubsub_subscription_iam.html#google_pubsub_subscription_iam_member

resource “google_pubsub_subscription_iam_member” “editor” {
 subscription = “your-subscription-name”
 role         = “roles/editor”
 member       = “user:jane@example.com”
}

So we need to know if the subscription has the specified member with the specified role.

Same thing could be done for pub sub topic

Also, there's 3 way to assign a member to a topic / subscription

google_pubsub_subscription_iam_policy: Authoritative. Sets the IAM policy for the subscription and replaces any existing policy already attached.

google_pubsub_subscription_iam_binding: Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. Other roles within the IAM policy for the subscription are preserved.

google_pubsub_subscription_iam_member: Non-authoritative. Updates the IAM policy to grant a role to a new member. Other members for the role for the subscription are preserved.

Thank you

**Comment by slevenick** [comment]
Yes that should be possible! I've done some work recently for other IAM policies, I believe that should be fairly easy to replicate for pubsub. I'll look into this

**Comment by slevenick** [comment]
The IAM policy resource proposed in #151 should be able to handle queries based on either binding or member.
