### ISSUE TITLE
Add support for InSpec 4

### ISSUE THREAD

**Issue by aaron-lane** [inspec/inspec-gcp#153]
## Detailed Description

inspec-gcp is currently [pinned to InSpec 3](https://github.com/inspec/inspec-gcp/blob/master/Gemfile#L8), which prevents it from working with InSpec 4. The pinning should be updated to include InSpec 4. 

## Context

Kitchen-Terraform 5 updated to InSpec 4, which means that users can not presently use inspec-gcp. [inspec-gcp: Can't find train plugin gcp](https://github.com/newcontext-oss/kitchen-terraform/issues/351).

## Possible Implementation

Change the dependency pinning to `'>= 3.0.25', '< 5'`.

**Comment by skpaterson** [comment]
Thanks for raising this @aaron-lane. The handling of attributes/inputs has changed in InSpec v4: 
https://github.com/inspec/inspec/issues/4260  
I'll update the pinning as soon as this is resolved InSpec side (or by reworking the controls here).

**Comment by skpaterson** [comment]
Turned out ^ was a non-issue so we can proceed.  As per the instructions here:
https://github.com/inspec/inspec#install-it-via-rubygemsorg
the pinning will be updated to:
```
gem 'inspec-bin'
```
