### ISSUE TITLE
Two entries for v0.11 in CHANGELOG; no associated tag

### ISSUE THREAD

**Issue by aaron-lane** [inspec/inspec-gcp#160]
# Describe the problem

There are [two](https://github.com/inspec/inspec-gcp/blob/master/CHANGELOG.md#v0110-2019-07-18) [entries](https://github.com/inspec/inspec-gcp/blob/master/CHANGELOG.md#v0110-2019-04-30) for v0.11 in the CHANGELOG. Additionally, no v0.11 tag exists.

## Possible Solution

Correct the version of the most recent release in the CHANGELOG and add tags for both the recent release and v0.11.

**Comment by skpaterson** [comment]
This should be resolved with #168 - feel free to reopen in case of issues.
