### ISSUE TITLE
Add support for regional google_compute_disk

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec-gcp#163]
## Detailed Description
`google_compute_disk` only supports zonal disks instead of supporting both zonal and regional disks.

## Context
When verifying the status of Google Cloud persistent disk, one should be able to test all types of disks. Not just zonal disks.

## Possible Implementation
Not sure. The attribute `zone` might get in the way of this though, I suspect.

**Comment by slevenick** [comment]
This was added via #164
