### ISSUE TITLE
Support ability to inspect GCS bucket labels so can assert upon them

### ISSUE THREAD

**Issue by djcoder100** [inspec/inspec-gcp#169]
## Detailed Description
As a secops user I would like to check for GCS label values and perform inspection tests on this in my cicd pipeline and report on any exceptions.

## Context

As secops developer need to check that GCP GCS bucket labels conform to any policies that are set by risk and control functions of an organisation to ensure lables are set on buckets and contents for the Google Cloud platform.

## Possible Implementation

Add as new property feature to the GCS resource in inspec for GCP:
https://www.inspec.io/docs/reference/resources/google_storage_bucket/

**Comment by slevenick** [comment]
Will be fixed via https://github.com/inspec/inspec-gcp/pull/244
