### ISSUE TITLE
found the documentation

### ISSUE THREAD

**Issue by darkn3rd** [inspec/inspec-gcp#17]
_**To document or not to document, that is the question!**_

I found the documentation embedded in the code, way cool!  Is there an auto-gen tool that can scoop up the class `name`, `desc`, and `example` into a markdown or something?  I remember at ChefConf18 hackathon, there was some talk about autogen of docs form these fields, but wasn't sure if this was out or how to get it.  I looked at the `Rakefile`, but there's no task to build docs yet.

**Comment by skpaterson** [comment]
Good question!  I'm not aware of any tool to auto-generate from those fields at this time but that would be great.  The longer term plan is hopefully to fold inspec-gcp into inspec core and so docs will eventually be built [with this InSpec documentation process](https://github.com/inspec/inspec/tree/master/docs) to be consistent with [existing resources](https://www.inspec.io/docs/reference/resources/).   If it would be useful in the short term, a task to build the docs is certainly something that could be explored.

**Comment by skpaterson** [comment]
Good suggestion - I'll convert those docs to markdown after https://github.com/inspec/inspec-gcp/pull/18 is completed.
