### ISSUE TITLE
GCP inspec library required for Dataproc

### ISSUE THREAD

**Issue by godstaker** [inspec/inspec-gcp#179]
We are currently implementing Dataproc at an enterprise level and was trying to implement a GCP inspec test. However there are currently no testing framework for Dataproc, within the GCP Inspec library.
Currently we have written some tests, that use 'google_compute_instance' to echeck if master and worker nodes have been created, lack public IPs and are in a 'Running State'.

We would like a similar type of test, with further types of testing.

**Comment by slevenick** [comment]
Thanks for the request!

Are there any particular parts of Dataproc that you would like to be able to use? Would it be primarily clusters, or more than just that?

I can look into adding resources for this

**Comment by godstaker** [comment]
Hi Sam,

Thank you for quick response, we mainly are mainly looking at it from a
security aspect:
Private/Public ip usage
No Internet access
Type of persistent disk use
Persistent disk cmek encryption
Naming convention
Components installed
Components gateway access

There are probably more aspects, to come.

Regards

Alvin Vassoodaven

**Comment by slevenick** [comment]
So specifically you would want to write tests against Dataproc Clusters? Which would be this object: https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.clusters#Cluster

**Comment by godstaker** [comment]
Hi Sam,

Yes this is pretty much, what we would like.

Regards

Alvin Vassoodaven

**Comment by godstaker** [comment]
Also, I would like to be able to verify that the Dataproc cluster has been created and working as it should, using GCP inspec.
I hope this makes sense.

**Comment by slevenick** [comment]
This is now available! See https://github.com/inspec/inspec-gcp/blob/master/docs/resources/google_dataproc_cluster.md
