### ISSUE TITLE
google_compute_router does not make the attached Cloud NAT Gateway information available.

### ISSUE THREAD

**Issue by lhasadreams** [inspec/inspec-gcp#189]
## Detailed Description
I would like to be able to determine if a Cloud NAT Gateway exists in a Project.

## Context
It is a guardrail check that my customers organisation requires to be checked to allow the use of GCP in their organisation.

## Possible Implementation
Speaking with @skpaterson  earlier, a couple suggestions were discussed:
(1) Create a new resource to interrogate the Cloud NAT Gateways available
  - google_compute_nats
  - google_compute_nat
(2) Modify the API schema that drives the magic module for google_compute_router to include access to the attached Cloud NAT Gateway(s).

**Comment by slevenick** [comment]
Hey @lhasadreams 

I'll look into creating this. I'll see if it's feasible to add as its own resource, but as a fall back I can add the fields to the `google_compute_router` resource.

**Comment by lhasadreams** [comment]
Many thanks for adding this functionality.
