### ISSUE TITLE
looking for Cloud Scheduler job -Inspec module

### ISSUE THREAD

**Issue by RishiR2** [inspec/inspec-gcp#191]
I would like to know inspec module for Cloud Scheduler service.

## Detailed Description
We are looking for Inspec model for Cloud Scheduler Job (pubsub,http,appengine_http), 
so want to know if there is any effort is already in place or near release.## Context

**Comment by slevenick** [comment]
Yeah, I can add this soon!

**Comment by RishiR2** [comment]
> Yeah, I can add this soon!
thank you Sam and looking forward to see the module

**Comment by slevenick** [comment]
This should now be available
