### ISSUE TITLE
Listing the google services on a Project.

### ISSUE THREAD

**Issue by lhasadreams** [inspec/inspec-gcp#192]
## Detailed Description
One of the checks I would like to make is that the correct services are enabled for GCP projects.
I can achieve this by creating an InSpec control to run an InSpec command resource to execute this:
gcloud services list --enabled --project=<my gcp project> --format=json
However that means that I need to run this separately to all my other checks that use the -t gcp:// train.

## Context
I would use it to verify that my Projects have the correct services enabled.

## Possible Implementation
Create a google_project_services InSpec resource

**Comment by slevenick** [comment]
Sounds reasonable. I can look into creating these resources this week

**Comment by skpaterson** [comment]
Closing this out based on #196
