### ISSUE TITLE
Support for additional parameters in inspec google_service_account_key

### ISSUE THREAD

**Issue by pradeepbhadani** [inspec/inspec-gcp#193]
As a DevOps engineer, I would like to check for service account keys managed by users and system separately. 

## Detailed Description
As a DevOps, I would like to identify the service account whose keys are created by users.

## Context
Current implementation does not have filter to distiguish between user managed keys and sysrem managed keys in returned result.

## Possible Implementation
`key_type` can be passed here https://github.com/inspec/inspec-gcp/blob/master/libraries/google_service_account_key.rb#L21
`KeyType` is a valid query type for `projects.serviceAccounts.keys.list`. Ref: https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts.keys/list

**Comment by pradeepbhadani** [comment]
Required fucntionality is available here https://github.com/inspec/inspec-gcp/blob/f6add3a4b804f4d5f0c720c1c141c0e315d5b619/libraries/google_service_account.rb#L39

I will add update the document to reflect this example.

**Comment by slevenick** [comment]
So this functionality already exists on `google_service_account`? Is there a need for anything else for this?

**Comment by pradeepbhadani** [comment]
@slevenick  - I have raised a PR(https://github.com/inspec/inspec-gcp/pull/199) to update documentation to make it more visible.
It took me sometime to find this functionality by looking at the code. So thought, might be easier for others if I can add an example in documentation.
