### ISSUE TITLE
google_compute_firewall does not allow you to determine the On/Off status of the logs

### ISSUE THREAD

**Issue by lhasadreams** [inspec/inspec-gcp#202]
## Detailed Description
google_compute_firewall missing the status of logs

## Context
I would like to be able to check that a firewall rule has logs turned on (or not off)

## Possible Implementation
The google API returns this log data, adjust google_compute_firewall do that it exposes it as well.

**Comment by slevenick** [comment]
Which field are you looking for? `logConfig.enable` on the firewall rule?

Should be easy enough to add a custom method to check that

**Comment by skpaterson** [comment]
Turns out the `logConfig` value is only returned by a later version of the `google-api-client`.  Bumping the version allows e.g.
```
    its('log_config.enable') {should be true}
```
Opened https://github.com/inspec/train/pull/531 to track this.

**Comment by slevenick** [comment]
This is now available in 1.0 `google_compute_firewall` via `log_config.enable_logging`
