### ISSUE TITLE
Ability To Get GCP Project Billing Account Info

### ISSUE THREAD

**Issue by seanmalloy** [inspec/inspec-gcp#204]
## Detailed Description

We would like to be able test/verify which billing account a GCP project is associated with.

https://cloud.google.com/billing/reference/rest/v1/ProjectBillingInfo

## Context

This is a useful feature when testing GCP project creation automation. So that we can verify that a correct billing account is assigned to a GCP project.

## Possible Implementation

Ideally this would be part of a `google_project`, docs/resources/google_project.md. But this is not a hard requirement.

**Comment by seanmalloy** [comment]
FYI ... @Fuzzy042 and @erjohnso

**Comment by slevenick** [comment]
Looking at creating this via a separate resource to utilize the REST endpoint. The current `google_project` resource uses the API client, but a different API client is required to make billing account calls

**Comment by slevenick** [comment]
Available via https://github.com/inspec/inspec-gcp/pull/205
