### ISSUE TITLE
Add the ability to check the IAM policy linked to a spanner instance

### ISSUE THREAD

**Issue by lhasadreams** [inspec/inspec-gcp#209]
## Detailed Description
Provide a new Resource that allows InSpec to test the data returned from:
gcloud spanner instances get-iam-policy <instance> --format json

## Context
To test the IAM policy on a spanner instance

I consulted with @skpaterson on this.

**Comment by lhasadreams** [comment]
@slevenick @skpaterson Please can I get you view on this.
Cheers
Adrian

**Comment by sukchomb** [comment]
Hi,

Would appreciate if this could be done at the earliest as our project has aggressive timelines to meet before X-mas.

Cheers,

Sukhjit

**Comment by slevenick** [comment]
This is available in 0.23.1
