### ISSUE TITLE
Spanner singular resource dose not behave the same way as other singular resources.

### ISSUE THREAD

**Issue by sukchomb** [inspec/inspec-gcp#210]
Spanner singular resource dose not behave the same way as other singular resources when the spanner name is passed in using the plural resource

# Describe the problem
The standard approach does not work:

google_spanner_instances(project: gcp_project_id).names.each do |name|
  spanner_instance = google_spanner_instance(project: gcp_project_id, name: name)

## Possible Solution
We have had to introduce an alternative approach where we take the last part of the name as in:

google_spanner_instances(project: gcp_project_id).names.each do |name|

    # Short term fix to get the last part of the 'name' to then drive the singular resource.
    # Example name -> "projects/pe-compliance2-ide-762e/instances/instance-with-no-labels-id"
    # String to be used is 'instance-with-no-labels-id'

    items = name.split('/')
    this_spanner_name = items[3]

    spanner_instance = google_spanner_instance(project: gcp_project_id, name: this_spanner_name)

**Comment by skpaterson** [comment]
Indeed, the name property in this case is the fully qualified name containing the full path.  The standard pattern does not work but you could always do something along these lines:
```
google_spanner_instances(project: gcp_project_id).names.each do |name|
    spanner_instance = google_spanner_instance(project: gcp_project_id, name: name.split('/').last)
...
```

**Comment by skpaterson** [comment]
The other solution would be to introduce an artificial 'base name' field to the resource in Magic Modules.

**Comment by sukchomb** [comment]
Ideally would like it to follow the standard pattern (as in for pubsub) as that brings consistency when reading/maintaining controls.

**Comment by slevenick** [comment]
I can absolutely add this, the only issue is that I wouldn't want to break users who already depend on the existing functionality. I believe it would be a breaking change to change this format

**Comment by lhasadreams** [comment]
Hi Sam,
I 100% agree with you and would not change it either.
It is not hard to get and use the info after all is it!
Cheers
Adrian

**Comment by sukchomb** [comment]
Closing as pattern exists to get the info.
