### ISSUE TITLE
dependency on inspec-bin should be optional, use of cinc-auditor-bin possible

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec-gcp#224]
The dependency to inspec-bin requires accepting Chef license. The community built cinc-auditor-bin should be a viable option for use of inspec-azure.
## Detailed Description

Cinc-auditor-bin gem should be an option to inspec-bin.
## Context

Users who want to build on top of OSS without accepting Chef license, cannot use Inspec-bin.
## Possible Implementation

Use `install_if` in Gemfile for inspec-bin/cinc-auditor-bin.
https://bundler.io/v1.10/man/gemfile.5.html#INSTALL_IF-install_if-

**Comment by tbugfinder** [comment]
https://github.com/inspec/inspec-aws/issues/166

**Comment by skpaterson** [comment]
Thanks for this suggestion. However, similarly to InSpec itself, the AWS, GCP and Azure cloud resource packs are Open Source so you are free to fork and update the Gemfile according to your needs. I'll close this out for now.
