### ISSUE TITLE
Unable to inspec database flags on Cloud SQL

### ISSUE THREAD

**Issue by mattbowes** [inspec/inspec-gcp#228]
## Detailed Description
We would like to be able to inspec database flags on Cloud SQL
Flag are available in the in the API at https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/instances/get

we tried
`  its('settings.database_flags.max_connections') { should cmp "on" }`

but get the error 
 ```
×  Database test-example-01 settings.database_flags.max_connections
     undefined method `max_connections' for #<Array:0x0000561ac1296a08>
```

## Context
We would like to verify that the flags are correct

**Comment by sukchomb** [comment]
Hi @mattbowes , this is how to do it,  see 'expected_database_flags' below of what I am testing for in my use case, adjust accordingly for yours.

```
google_sql_database_instances(project: gcp_project_id).where(instance_version: /MYSQL_/).instance_names.each do |instance_name|

    this_instance = google_sql_database_instance(project: gcp_project_id, database: instance_name)

    # Structure in response database_flags=>[{:name=>"general_log", :value=>"on"}, {:name=>"log_output", :value=>"FILE"}],

    # Add more flags that should exist as need arises
    expected_database_flags=[{"name" => "general_log"   , "value"   => "on"  },
                             {"name" => "log_output"    , "value"   => "FILE"},
                             {"name" => "slow_query_log", "value"   => "on"  }]
                

     if this_instance.settings.item.has_key?(:database_flags)

       this_instance_db_flags = this_instance.settings.item.fetch(:database_flags)

       #settings.databaseFlags is an array containing one or more hashes, there is one hash for each flag and each hash has a key pair => name and value

       expected_database_flags.each do | expected_db_flag|
 
         expected_flag_name  = expected_db_flag.fetch('name')
         expected_flag_value = expected_db_flag.fetch('value')

         #puts "flag_name is #{expected_flag_name} value is #{expected_flag_value}"

         # Find the expected flag in this instance
         this_instance_db_flag_array = this_instance_db_flags.select { |flag| flag[:name] == expected_flag_name }

         if !this_instance_db_flag_array.empty?

           this_instance_db_flag_hash = this_instance_db_flag_array[0]
         
           describe "MYSQL instance #{instance_name}, database flag '#{expected_flag_name}'" do
             subject{"#{this_instance_db_flag_hash.fetch(:name)} = #{this_instance_db_flag_hash.fetch(:value)}"}

             it{ should eq "#{expected_flag_name} = #{expected_flag_value}" }
           end

         else
           # Expected flag was not setup in this instance
           describe "MYSQL instance #{instance_name}, database flag '#{expected_flag_name}'" do
             subject{''}

             it{ should eq "#{expected_flag_name} = #{expected_flag_value}" }
           end

         end
       end

     else
       describe "MYSQL instance #{instance_name}, has NO database flags, they" do
         subject{''}

         it{should include "'general_log' with value = 'on'"  }
         it{should include "'log_output' with value = 'FILE'"}
         it{should include "'slow_query_log' with value = 'on'"}
       end
     end
  end
```

**Comment by sukchomb** [comment]
Hi @mattbowes , This updated code will work with the release of gcp resource pack version 1.0

`  # Add more flags that should exist as need arises
  expected_database_flags=[{"name" => "general_log"   , "value" => "on"  },
                           {"name" => "log_output"    , "value" => "FILE"},
                           {"name" => "slow_query_log", "value" => "on"  }]

  google_sql_database_instances(project: gcp_project_id).where(instance_version: /MYSQL_/).instance_names.each do |instance_name|

    this_instance = google_sql_database_instance(project: gcp_project_id, database: instance_name)

    if this_instance.settings.database_flags.respond_to? :each

      ## this_instance.settings.database_flags.each do |flag|
      ##   puts "DB Settings entry is #{flag.inspect}' || #{flag.name}' '#{flag.value}'"
      ## end

      expected_database_flags.each do | expected_db_flag|
 
        expected_flag_name  = expected_db_flag.fetch('name')
        expected_flag_value = expected_db_flag.fetch('value')

        found_db_flag = false

        this_instance.settings.database_flags.each do |flag|

          ## puts "FLAGS =>#{flag.name} = #{flag.value}"

          if expected_flag_name.eql?(flag.name)

            found_db_flag = true

            describe "MYSQL instance #{instance_name}, database flags" do
              subject{"#{flag.name} = #{flag.value}"}
              it{ should include "#{expected_flag_name} = #{expected_flag_value}" }
            end

            break
          end
        end

        if !found_db_flag  # Expected flag was not setup in this instance

          describe "MYSQL instance #{instance_name}, database flags" do
            subject{''}
            it{ should include "#{expected_flag_name} = #{expected_flag_value}" }
          end
        end
      end

    else  ## No Flags defined

       expected_database_flags.each do | expected_db_flag|
 
         describe "MYSQL instance #{instance_name}, has NO database flags, it" do
           subject{''}
           it {should include  "#{expected_db_flag.fetch('name')} = #{expected_db_flag.fetch('value')}"}
         end

       end
    end
  end
end`

**Comment by mattbowes** [comment]
thanks for the tip @sukchomb. I am going to close this
