### ISSUE TITLE
google_container_regional_cluster() unable to test 'pod_security_policy_config' property

### ISSUE THREAD

**Issue by sukchomb** [inspec/inspec-gcp#229]
# Describe the problem
I as owner of the GCP platform, when I use the gcp inspec resource 'google_container_regional_cluster()' 

I specifically want to test the 'pod_security_policy_config' property of the cluster

However this property is not documented in https://www.inspec.io/docs/reference/resources/google_container_regional_cluster/ 

Furthermore the property is returned when using the beta version of the api "gcloud beta container clusters describe "

but is not returned when using the "solid" version.

Please advise when the beta version is to become "solid"?
## Possible Solution
The beta version of the API could potentially be used but is not ideal for us.

**Comment by slevenick** [comment]
I don't have any information on when this field will be moved from beta to GA, but I would guess that it will take a while.

I'm in the process of doing a large migration of some of the InSpec resources that will allow for querying of the beta APIs via InSpec resources that should make this available

**Comment by slevenick** [comment]
This will be available via https://github.com/inspec/inspec-gcp/pull/226 on the new combined `google_container_cluster`

**Comment by slevenick** [comment]
Available on the `google_container_cluster` in 1.0
