### ISSUE TITLE
Enhancement: Support Fuzzy Match with Instance Group Name

### ISSUE THREAD

**Issue by darkn3rd** [inspec/inspec-gcp#23]
## Summary

Please support relative matching for instance groups.  Doing an explicit match for a particular instance group for instance groups that are autogenerated by another resource, like GKE, makes this resource have extremely low utility.

For example, I create a GKE cluster called `guestbook`, I get this:

```bash
$ gcloud compute instance-groups list
NAME                                     LOCATION    SCOPE  NETWORK  MANAGED  INSTANCES
gke-guestbook-default-pool-d84d40bd-grp  us-east1-b  zone   default  Yes      3
```

I know I'll get `/^gke-guestbook-default-pool-.*-grp$/`, but I don't know dynamically generated number embedded into this.

## WORKAROUND 

I would prefer to use whatever libraries I could use to fetch state and use to test another state.  This what I have to do:

```ruby
POOL_HASH=`gcloud container clusters describe guestbook | grep grp | head -1 | awk -F- '{ print $(NF-1) }'`.chomp
POOL_NAME="gke-guestbook-default-pool-#{POOL_HASH}-grp"

describe google_compute_instance_group(project: PROJECT_NAME, zone: CLUSTER_ZONE, name: POOL_NAME) do
  its('name') { should eq POOL_NAME }
  its('size') { should eq 3 }
  its('zone') { should match CLUSTER_ZONE }
  its('kind') { should eq 'compute#instanceGroup' }
end
```

**Comment by darkn3rd** [comment]
Actually, now that I have played with a few resources, you really need the ability to find set a systems based on name, tags, metadata, etc.  Especially names and tags.  From each of these return, you can run tests on them.  

For static systems during _iron age_ of computing, static names may work, but for cloud platforms (Azure, GCP, AWS, etc), where things are ephemeral, you really need a way to pull a system out based on their name.  Otherwise, this have very limited utility in current implementation.

**Comment by skpaterson** [comment]
The following PR adds plural resources such that you can e.g. loop over all firewall rules / compute instances / zones:
https://github.com/inspec/inspec-gcp/pull/18
This will also allow looping over resources selectively where a given property exists e.g. firewall rules which apply only on direction 'INGRESS'.  Your feedback is really useful here to build out which properties should be included.

**Comment by skpaterson** [comment]
With #32 it’s possible to loop across all instance groups or filter on names e.g. 

```
google_compute_instance_groups(project: PROJECT_NAME, zone: CLUSTER_ZONE).where(instance_group_name: /^gke-guestbook-default-pool-.*-grp$/).instance_group_names.each do |instance_group_name|
  describe google_compute_instance_group(project: PROJECT_NAME, zone: CLUSTER_ZONE, name: instance_group_name) do
    it { should exist }
    its('size') { should be > 0 }
  end
end
```

See https://github.com/inspec/inspec-gcp/blob/master/docs/resources/google_compute_instance_groups.md for more details.  Worth mentioning the loop could also loop over all projects and zones.
