### ISSUE TITLE
google_storage_buckets missing retention_policy Method

### ISSUE THREAD

**Issue by pburnet-lbg** [inspec/inspec-gcp#247]
The prior version of google_storage_buckets exposed both

retention_policy methods.

This now seems to be missing.

# Describe the problem

For retention policy my previous control used:

    describe google_storage_bucket(name: bucket_name) do
      its('retention_policy.retention_period') {should eq 39446190} #  15 months
      its('retention_policy.is_locked') {should eq true}

without retention policy as a method this is not possible.

retention_policy should be exposed as a method so that i can have access to:

"retentionPolicy"=>{"retentionPeriod"=>"10", "effectiveTime"=>"2019-10-03T13:12:36.529Z", "isLocked"=>true},
## Possible Solution

Add retention_policy back as a method

**Comment by slevenick** [comment]
Use version 1.3.0 for this to be added back
