### ISSUE TITLE
google_storage_bucket missing encryption method

### ISSUE THREAD

**Issue by pburnet-lbg** [inspec/inspec-gcp#248]
The prior version of google_storage_buckets exposed encryption as a method

This now seems to be missing.

# Describe the problem

my previous control

          describe bucket do
        it { should respond_to :encryption}
        if bucket.respond_to? :encryption
        its('encryption') { should_not be nil}
        end
      end
      if bucket.respond_to? :encryption
        items=bucket.encryption.item[:default_kms_key_name].split('/')
        project=items[1]
        location=items[3]
        keyring=items[5]
        key=items[7]
        kms = google_kms_crypto_key(project:project,location:location,key_ring_name:keyring,name:key)
        describe bucket_name + ' ' + kms.version_template.item[:protection_level] do
          it {should eq bucket_name + ' HSM'}

encryption  should be exposed as a method so that i can have access to:

 "encryption"=>
  {"defaultKmsKeyName"=>
    "projects/compliance1-infraprov-9cc2/locations/europe-west2/keyRings/compliance-key-ring-sese/cryptoKeys/compliance1-infraprov-HSMprotected"},

## Possible Solution

Add encryption back as a method

**Comment by slevenick** [comment]
Use version 1.3.0 for this to be added back
