### ISSUE TITLE
metadata_value_by_key on google_compute_instance returns error

### ISSUE THREAD

**Issue by mattbowes** [inspec/inspec-gcp#257]
Using profile `1.4.0` and calling  `metadata_value_by_key` on `google_compute_instance` the following error is returned

``undefined method `item' for #<Hash:0x00007f05967f0e70>``

# Describe the problem
```
describe google_compute_instance(project: gcp_project_id, zone: gce_zones, name: vm).metadata_value_by_key('serial-port-enable') do
    it { should be false }
  end
```

returns 

```
undefined method `item' for #<Hash:0x00007f05967f0e70>
```

**Comment by slevenick** [comment]
Fixed via https://github.com/inspec/inspec-gcp/pull/259
