### ISSUE TITLE
Standardize names, tests, and examples of matchers

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec-gcp#26]
While matchers and properties are both methods on the resource, they are written and used differently and have different UX impacts.

Properties do not take arguments, may return any return value, and should read well when used with `its`.  Their names never end in a question mark.  Examples might include lists of IDs, names, settings, etc.  They are usually used with the [universal matchers](https://www.inspec.io/docs/reference/matchers/), such as `include`, `cmp`, `eq` and so on.

```ruby
# Property example
describe google_compute_firewall(...) do
  its('direction') { should eq "INGRESS" }
end
```

Matchers are methods that always end in a question mark, are expected to return true or false, may take arguments, and should read well when used with `it` after RSpec name mangling.  Low-level matchers might test a status (`running?` => `be_running`) while high-level matchers can perform sophisticated queries (`has_permission?(action:  :delete, resource: '*')`).

```ruby
# Matcher example
describe google_compute_firewall(...) do
  # Fictional UX
  it { should allow_ssh }
  # Fictional, more general UX with args:
  it { should allow_in(port: 22) }
  # Actual current UX when used as a matcher
  it { should be_allowed_ssh }
end
```

Matchers are subject to RSpec matcher name aliasing.  Methods that begin with the string 'has_' will be exposed as a matcher beginning with 'have_'.  All other methods ending with a question mark will have a 'be_' prefixed.  You can override this behavior using RSpec::Matcher.alias_matcher.

All that background aside....

Use matchers as *matchers* in tests and examples.
```ruby
describe google_compute_firewall(...) do
  # Do this (or a more fluent version of it):
  it { should be_allowed_ssh }

  # Not this (treating a matcher as a property):
  its(allowed_ssh?) { should be true }
end
```

Aim to write matchers that will read "fluently" after name mangling.

**Comment by skpaterson** [comment]
Closing this out as we will standardize this as part of the ongoing MM resource generation.
