### ISSUE TITLE
Compute instance metadata keys error

### ISSUE THREAD

**Issue by pburnet-lbg** [inspec/inspec-gcp#261]
For the metadata helpers the methods don't seem to be working

metadata_keys
NoMethodError: undefined method `item' for #<Hash:0x0000000007e19a40>
from libraries/google_compute_instance.rb:179:in `metadata_keys'

similiarly for

metadata_value_by_key  and etadata_values 

  def metadata_keys
    return [] if !defined?(@metadata) || @metadata.nil?
    @metadata.item[:items].map { |m| m[:key] }
  end

# Describe the problem

helper method seems to be incorrect

**Comment by mattbowes** [comment]
@pburnet-lbg  this looks the same as issue #257

**Comment by Schwad** [comment]
Hello! 👋 

For those looking into this, it appears that `@metadata`, at least in some cases, is getting assigned as a `Hash` object. https://github.com/inspec/inspec-gcp/blob/master/libraries/google_compute_instance.rb#L177

I would manually test-debug but would need to hook up to a new test gcp instance

```
def metadata_keys
    return [] if !defined?(@metadata) || @metadata.nil?
    @metadata.item[:items].map { |m| m[:key] }
  end

  def metadata_values
    return [] if !defined?(@metadata) || @metadata.nil?
    @metadata.item[:items].map { |m| m[:value] }
  end

  def metadata_value_by_key(metadata_key)
    return [] if !defined?(@metadata) || @metadata.nil?
    @metadata.item[:items].each do |item|
      if item[:key] == metadata_key
        return item[:value]
      end
    end
    []
  end
```

As noted above, likely all of these are affected. If debugging I would check if `@metadata[:item][:items]` succeeded or just `@metadata[:items]`. However it's actually formed here.

**Comment by slevenick** [comment]
This should be fixed now via https://github.com/inspec/inspec-gcp/pull/259
