### ISSUE TITLE
Expose network peers via google_compute_networks.

### ISSUE THREAD

**Issue by pburnet-lbg** [inspec/inspec-gcp#274]
Network peers do not get exposed when doing google_compute _networks lookups although the data is available via raw_data method

## Detailed Description

Magic modules needs to be updated ideally but this is the manual fix i made in google_compute_networks.rb

 filter_table_config.add(:peerings, field: :peerings)

i can the do this in my control

network =  google_compute_networks_pb(project: gcp_project_id)
  if !network.peerings.first.nil?
    network.peerings.each do | network_config |
      network_config['peerings'].each do |peer|
        puts "this is the found peer: #{peer['name']} in network #{peer['network']}"

## Context

This is required so that i can check the configuration of network peerings in our estate to ensure that we are not peering to networks outside of our control.

## Possible Implementation

Update magic modules to add peerings.

**Comment by clintoncwolfe** [comment]
This was implemented in #280
