### ISSUE TITLE
subject.settings.item is undefined in v1.8.0

### ISSUE THREAD

**Issue by g-awmalik** [inspec/inspec-gcp#321]
For the google_sql_database_instance resource, subject.settings.item has been throwing the following error in v1.8.0:

**undefined method `item' for #<#<Class:0x0000561405f92878>::GoogleInSpec::SQL::Property::DatabaseInstanceSettings:0x0000561407320318>**

This used to work just fine up until 0.21.4.

Was the item method/object deprecated at some point? If so, what are the alternatives?

More specifically, where can we find these settings now:

      activation_policy: "ALWAYS",
      data_disk_size_gb: 10,
      data_disk_type: "PD_SSD",
      kind: "sql#settings",
      pricing_plan: "PER_USE",
      replication_type: "SYNCHRONOUS",
      storage_auto_resize: true,
      storage_auto_resize_limit: 0,
      tier: tier,

**Comment by levid0s** [comment]
what's the fix version for this please?
