### ISSUE TITLE
google_project resource works with project ID/number instead of name as seen in the docs

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec-gcp#39]
I'm trying inspec-gcp for the first time. I followed the steps and I have implemented the following InSpec resource:

```
    describe google_project(project: File.read('./terraform-gcp-provider-config-project')) do
        it { should exist }
        its('lifecycle_state') { should eq "ACTIVE" }
    end
```

The file shown above contains the project *name* in GCP. When executing inspec, I get an error saying:
```
×  Project
     The caller does not have permission
```

When I pass the project *ID* or the project *number*, instead, the resource runs as normal passing the test successfully.

The [documentation](https://github.com/inspec/inspec-gcp/blob/master/docs/resources/google_project.md#syntax) states that the "_`google_project` resource block declares the tests for a single GCP project by name._", so I am not sure who's right in this instance: the code or the documentation?

Thank you.

**Comment by skpaterson** [comment]
You're absolutely right, the `google_project` docs are confusing in their current state.   I'll update these to reflect that the resource works with either `project_id` or  `project_number` as argument.  Thanks for raising this, all the resource documents are hand-crafted so errors can creep in!
