### ISSUE TITLE
latest version v1.11.4 inspec getting error Don't understand inspec profile.

### ISSUE THREAD

**Issue by avilashjena** [inspec/inspec-gcp#444]
latest version [v1.11.4](https://github.com/inspec/inspec-gcp/releases/tag/v1.11.4) inspec getting error Don't understand inspec profile in /Users/****/.inspec/cache/2cfe7bf0976f6fff882011b681e70a1cd87f1d459e5ccc79ae78c5ba33fb7945.tar.gz, it doesn't look like a supported profile structure.
# Describe the problem

Go to profile location and running command inspec exec . -t gcp:// --input gcp_project_id='******'

and getting bellow error:

Don't understand inspec profile in /Users/*****/.inspec/cache/2cfe7bf0976f6fff882011b681e70a1cd87f1d459e5ccc79ae78c5ba33fb7945.tar.gz, it doesn't look like a supported profile structure.

## Possible Solution

##Work around 
in inspec.yml i have pinned the last version

#attributes:
inputs:
- name: gcp_project_id
  required: true
  description: The GCP project identifier.
depends:
- name: inspec-gcp
  url: https://github.com/inspec/inspec-gcp/archive/refs/tags/v1.11.1.tar.gz
supports:
- platform: gcp

**Comment by sophhu** [comment]
We are having the same problem too, it seems like the tar.gz file that is downloaded is the latest 1.11.4 version - not sure if that is related?
![Screenshot 2023-08-02 at 2 57 56 PM](https://github.com/inspec/inspec-gcp/assets/97482837/4078d954-977b-4575-ba0e-53657cd5bda5)

**Comment by levid0s** [comment]
Having the same issue. Are there any workarounds?

**Comment by brettcurtis** [comment]
The latest version I've been able to use is: ` url: https://github.com/inspec/inspec-gcp/archive/v1.11.3.tar.gz`

**Comment by sa-progress** [comment]
We are looking into this, we will get back on this.
