### ISSUE TITLE
Support regional clusters

### ISSUE THREAD

**Issue by matt-simons** [inspec/inspec-gcp#65]
Presently `google_container_cluster` only supports zonal clusters as it uses the `get_zone_cluster` function in https://github.com/googleapis/google-api-ruby-client/blob/master/generated/google/apis/container_v1beta1/service.rb

If instead it used `get_project_location_cluster` it would support both zonal and regional clusters.

Similarly `google_container_clusters` could support both zonal and regional clusters if it used `list_project_location_clusters` function.

Happy to create a pull request to resolve this.

**Comment by skpaterson** [comment]
Thanks @matt-simons that makes good sense.  PR's are always welcome!  Otherwise will happily pick this up at the next opportunity.

**Comment by slevenick** [comment]
Now available here: https://github.com/inspec/inspec-gcp/blob/master/libraries/google_container_regional_cluster.rb

And https://github.com/inspec/inspec-gcp/blob/master/libraries/google_container_regional_clusters.rb

**Comment by skpaterson** [comment]
Thanks @slevenick !  @pinterb I'll close this out but feel free to reopen if you encounter any issues.
