### ISSUE TITLE
JUnit, JSON Reporters not working 

### ISSUE THREAD

**Issue by ali-himindz** [inspec/inspec-gcp#89]
Hi,
I am running inspec with 
--reporter cli junit:/src/TEST-project-validation.xml json:/src/TEST-project-validation.json

with inspec-gcp
But somehow I am not getting the Junit or Json reports.
The results are only appearing on the screen.

Are other reporters supported?
thanks
Ali

**Comment by skpaterson** [comment]
hi @ali-himindz - reporters should work fine.  For example, I get expected outputs from:
```
inspec exec . -t gcp:// --attributes=myattributes.yaml --reporter cli junit:test.xml json:output.json
```
Can you confirm the full command being run as well as the InSpec version?

**Comment by skpaterson** [comment]
Closing out for now as this cannot be reproduced.
